services:
  # =========================================
  # 1. CAPA DE DATOS (PostgreSQL + PostGIS)
  # =========================================
  database:
    image: postgis/postgis:17-3.4-alpine
    container_name: gcp-sql-local
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./infra/local-init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-local
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
      - app-network

  # =========================================
  # 2. MICROSERVICIOS
  # =========================================

  # --- AUTH SERVICE ---
  auth-service:
    build:
      context: ./backend/services/auth
      dockerfile: Dockerfile
    container_name: auth-service
    restart: on-failure
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgres://admin:root@database:5432/usuarios_db
      # Seguridad JWT
      - JWT_SECRET=MiSecretoSuperSeguro2025ParaDesarrolloLocal
      - JWT_REFRESH_SECRET=MiRefreshSecretSuperSeguro2025ParaDesarrolloLocal
      - JWT_EXPIRES_IN=1h
      - SERVICE_TOKEN=MiTokenS2S123
      # Conexiones Salientes
      - USUARIOS_SERVICE_URL=http://usuarios-service:3000
      - CATALOG_SERVICE_URL = http://catalog-service:3000
      - ORDERS_SERVICE_URL = http://orders-service:3000
      - FINANCE_SERVICE_URL = http://finance-service:3000
      - WAREHOUSE_SERVICE_URL = http://warehouse-service:3000
      - AUTH_SERVICE_URL = http://auth-service:3000
    depends_on:
      - database
    networks:
      - app-network

  # --- USUARIOS SERVICE ---
  usuarios-service:
    build:
      context: ./backend/services/usuarios
      dockerfile: Dockerfile
    container_name: usuarios-service
    restart: on-failure
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgres://admin:root@database:5432/usuarios_db
      - JWT_SECRET=MiSecretoSuperSeguro2025ParaDesarrolloLocal
      - SERVICE_TOKEN=MiTokenS2S123
      # Conexiones Salientes
      - USUARIOS_SERVICE_URL=http://usuarios-service:3000
      - CATALOG_SERVICE_URL = http://catalog-service:3000
      - ORDERS_SERVICE_URL = http://orders-service:3000
      - FINANCE_SERVICE_URL = http://finance-service:3000
      - WAREHOUSE_SERVICE_URL = http://warehouse-service:3000
      - AUTH_SERVICE_URL = http://auth-service:3000
    depends_on:
      - database
    networks:
      - app-network

  # --- CATALOG SERVICE ---
  catalog-service:
    build:
      context: ./backend/services/catalog
      dockerfile: Dockerfile
    container_name: catalog-service
    restart: on-failure
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgres://admin:root@database:5432/catalog_db
      - JWT_SECRET=MiSecretoSuperSeguro2025ParaDesarrolloLocal
      - SERVICE_TOKEN=MiTokenS2S123
      # Conexiones Salientes
      - USUARIOS_SERVICE_URL=http://usuarios-service:3000
      - CATALOG_SERVICE_URL=http://catalog-service:3000
      - ORDERS_SERVICE_URL=http://orders-service:3000
      - FINANCE_SERVICE_URL= http://finance-service:3000
      - WAREHOUSE_SERVICE_URL=http://warehouse-service:3000
      - AUTH_SERVICE_URL=http://auth-service:3000
    depends_on:
      - database
    networks:
      - app-network

  # --- ORDERS SERVICE ---
  orders-service:
    build:
      context: ./backend/services/orders
      dockerfile: Dockerfile
    container_name: orders-service
    restart: on-failure
    ports:
      - "3004:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgres://admin:root@database:5432/orders_db
      - JWT_SECRET=MiSecretoSuperSeguro2025ParaDesarrolloLocal
      - SERVICE_TOKEN=MiTokenS2S123
      # Conexiones Salientes
      - USUARIOS_SERVICE_URL=http://usuarios-service:3000
      - CATALOG_SERVICE_URL=http://catalog-service:3000
      - ORDERS_SERVICE_URL=http://orders-service:3000
      - FINANCE_SERVICE_URL=http://finance-service:3000
      - WAREHOUSE_SERVICE_URL=http://warehouse-service:3000
      - AUTH_SERVICE_URL=http://auth-service:3000
    depends_on:
      - database
      - catalog-service
      - warehouse-service
    networks:
      - app-network

  # --- LOGISTICS SERVICE ---
  logistics-service:
    build:
      context: ./backend/services/logistics
      dockerfile: Dockerfile
    container_name: logistics-service
    restart: on-failure
    ports:
      - "3006:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgres://admin:root@database:5432/logistics_db
      - JWT_SECRET=MiSecretoSuperSeguro2025ParaDesarrolloLocal
      - SERVICE_TOKEN=MiTokenS2S123
      # Conexiones Salientes
      - USUARIOS_SERVICE_URL=http://usuarios-service:3000
      - CATALOG_SERVICE_URL=http://catalog-service:3000
      - ORDERS_SERVICE_URL=http://orders-service:3000
      - FINANCE_SERVICE_URL=http://finance-service:3000
      - WAREHOUSE_SERVICE_URL=http://warehouse-service:3000
      - AUTH_SERVICE_URL=http://auth-service:3000
    depends_on:
      - database
      - catalog-service
      - orders-service
    networks:
      - app-network

  # --- FINANCE SERVICE ---
  finance-service:
    build:
      context: ./backend/services/finance
      dockerfile: Dockerfile
    container_name: finance-service
    restart: on-failure
    ports:
      - "3007:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgres://admin:root@database:5432/finance_db
      - JWT_SECRET=MiSecretoSuperSeguro2025ParaDesarrolloLocal
      - SERVICE_TOKEN=MiTokenS2S123
      # Conexiones Salientes
      - USUARIOS_SERVICE_URL=http://usuarios-service:3000
      - CATALOG_SERVICE_URL=http://catalog-service:3000
      - ORDERS_SERVICE_URL=http://orders-service:3000
      - FINANCE_SERVICE_URL=http://finance-service:3000
      - WAREHOUSE_SERVICE_URL=http://warehouse-service:3000
      - AUTH_SERVICE_URL=http://auth-service:3000
    depends_on:
      - database
      - orders-service
    networks:
      - app-network

  # --- WAREHOUSE SERVICE ---
  warehouse-service:
    build:
      context: ./backend/services/warehouse
      dockerfile: Dockerfile
    container_name: warehouse-service
    restart: on-failure
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgres://admin:root@database:5432/warehouse_db
      - JWT_SECRET=MiSecretoSuperSeguro2025ParaDesarrolloLocal
      - SERVICE_TOKEN=MiTokenS2S123
      # Conexiones Salientes
      - USUARIOS_SERVICE_URL=http://usuarios-service:3000
      - CATALOG_SERVICE_URL=http://catalog-service:3000
      - ORDERS_SERVICE_URL=http://orders-service:3000
      - FINANCE_SERVICE_URL=http://finance-service:3000
      - WAREHOUSE_SERVICE_URL=http://warehouse-service:3000
      - AUTH_SERVICE_URL=http://auth-service:3000
    depends_on:
      - database
    networks:
      - app-network
    # Healthcheck para asegurar que responda
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

# =========================================
# 3. REDES Y VOLÃšMENES
# =========================================
networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
