openapi: 3.0.0
info:
  title: Ventas Service API
  version: 0.1.0
paths:
  /ventas:
    post:
      summary: Crear venta
      requestBody:
        required: true
      responses:
        '201':
          description: Created
  /ventas/{id}:
    get:
      summary: Obtener venta por id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
